# ----------------------------------------------------------------------------------------
#                             THEME MEOW CONFIGURATION
#                               Author: 小橘猫chanwj
#                  GITHUB: https://github.com/chanwj/hexo-theme-meow
#                  DOCUMENTATION: https://chanwj.github.io/meow/docs
#                  PREVIEW STATION：https://chanwj.github.io/meow
# ----------------------------------------------------------------------------------------

# Theme Version (Automatically Updated By Theme)
version: v3.0.0 # Please DON'T modify it by yourself

# Website Info
info:
  # Site Favicon
  favicon: assets/images/Hexo-Theme-MEOW.ico
  # Site Logo
  logo: assets/images/Hexo-Theme-MEOW.png
  # Author Avatar
  avatar: https://q1.qlogo.cn/g?b=qq&nk=763608788&s=640
  # The root directory of your website, default: /
  # If your site is in a subdirectory(e.g. username.github.io/subdirectory), set root to /subdirectory/
  # root: /meow/
  start_date: 2024-04-02 22:16:20 # Format should be as same as date_format and time_format of root config

# Theme Color & Mode
color:
  # Light Mode
  light:
    theme_color: '#FFB347'
    # Dark Mode
  dark:
    theme_color: '#FFE4E1'
  # Light/Dark Mode Configuration
  mode:
    default: light
    switch_enable: true

# Icon Configuration
icon:
  # Icon Style Type
  type: uc

# Font Customization
font:
  custom: true # Whether to use custom font
  default_font_link: assets/fonts/vivoSans-Regular/result.css # Url of default font
  default_font_family: "'vivo Sans', 'PingFang SC', 'Microsoft YaHei', Sans-serif, Serif" # Define default fonts
  title_font_link: https://registry.npmmirror.com/@chinese-fonts/mkzyt/2.0.1/files/dist/猫啃珠圆体/result.css # Url of title font
  title_font_family: "'MaokenZhuyuanTi', 'vivo Sans', 'PingFang SC', 'Microsoft YaHei', Sans-serif, Serif" # Define title fonts
  code_font_link: # Url of code font
  code_font_family: # Define code fonts

# Layout Configuration
layout:
  # main_max_width: 1400px

# Navigation Bar
menu:
  articles || uc-article:
    archives: /archives || uc-archive
    categories: /categories || uc-category
    tags: /tags || uc-tag
  about || uc-about:
    site: /aboutsite || uc-site
    author: /aboutme || uc-face
    essay: /essay || uc-sun
  links || uc-link:
    albums: /albums || uc-picture
    bookmarks: /bookmarks || uc-bookmark
    friends: /friends || uc-friend
  comments: /comments || uc-note
  # articles || uc-article:
  #   archives: /archives || uc-archive
  #   categories: /categories || uc-category
  #   tags: /tags || uc-tag

# Search Function
search:
  enable: true # Whether to enable search function

# Banner Configuration
banner:
  # Whether to enable Banner
  enable: true
  # Background image of banner under light/dark mode
  image:
    light: assets/images/wallhaven-5yl597.webp
    dark: assets/images/wallhaven-e7zogk.webp
    is_fixed: true # Whether the image is fixed as background or scrollable with banner, true or false
    position: center top # horizontal(left/center/right) vertical(top/center/bottom)
    repeat: no-repeat # repeat/repeat-x/repeat-y/no-repeat
  # Banner title
  title:
    enable: true # Whether to show title
    text: 「 MEOW 」 # Title text
  # Banner subtitle
  subtitle:
    enable: true # Whether to show subtitle
    # Subtitle text (Data type: Array)
    text:
      - "简洁可爱的响应式Hexo主题🐱"
      - "超级适合用来发布小说、图片、同人等作品♥️"
      - "A cute and responsive theme for Hexo"
      - "🐈喵呜～"
    effect: true # Typewriter effect, true or false. If false, only show the first text.
    type_speed: 100 # Typing speed (ms)
    back_speed: 150 # Backing speed (ms)
    start_delay: 500 # Start delay (ms)
    back_delay: 1500 # Backing delay (ms)
    loop: true # Whether to loop, true or false
    smart_backspace: true # Whether to enable smart backspace, true or false
    fade_out: true # Whether to enable fade out effect, true or false
    shuffle: false # Whether to shuffle the text list
  title_color: # Title color under light/dark mode
    light: '#fff'
    dark: '#f3f3f2'

# Sidebar At Homepage
sidebar:
  enable: true # Whether to show sidebar
  position: left # Sidebar position, left or right
  show_on_small_screen: true # Whether to show sidebar at the bottom of homepage on small screen
  # Information card
  info:
    enable: true # Whether to show information card
    type: author # Which type of information to show, site or author
    status: # Status next to the avatar
      emoji: 🐱 # false or emoji
      desc: 元气满满～ # Describe the status
    link: /aboutme # Url for image clicking
    desc: 一只既敲代码又写小说的橘猫 # Describe yourself or say something
    statistic: true # Whether to show the total number of articles, categories and tags
    social: # Social profiles
      enable: true # Whether to show social module
      list: # Social type: social icon || social link
        email: brand-mail || contact@jumao.simplelogin.com
        github: brand-github || https://github.com/chanwj
        qq: brand-qq || https://qm.qq.com/q/NLqvCFlBeA
        steam: brand-steam || https://steamcommunity.com/id/midnightexpress/
        xiaohongshu: custom-xiaohongshu || https://www.xiaohongshu.com/user/profile/5711d9b884edcd2b70217559
  # Show announcement card, false or announcement text, markdown available
  announcement: Hi～这里是Hexo主题<font style="color:#FFB347">**Meow**</font>的专属网站，提供主题文档以及各种demo，希望能够帮助到您💗<br><br>如果您在使用本主题的过程中遇到问题，请到[Github Issues](https://github.com/chanwj/hexo-theme-meow/issues)进行反馈。
  # Links card
  links:
    enable: true # Whether to show additional links
    title: 快速直达 # The title of links card
    list: # List of links. link name: url
      📦 Meow项目仓库: https://github.com/chanwj/hexo-theme-meow
      📋 Meow主题指南: /posts/meow-guide
  # Categories card
  categories:
    enable: true # Whether to show categories card
    depth: 0 # Levels of categories to be displayed. 0 displays all categories and child categories; 1 displays only top level categories. Better be less than 3.
  tags: true # Whether to show tags card

# Homepage Customization
home:
  cover_position: top # top or left

# Articles Customization
article:
  excerpt_length: 200

# Markdown Style
markdown:
  # link_icon: true # Whether to show link icon

# Page View Counting
page_view:
  enable: true # Whether to show page view statistic
  url: https://cn.vercount.one/js # Counter API url
  site_pv: true # Site's page view
  site_uv: true # Site unique visitor
  page_pv: true # Page view

# Footer Customization
footer:
  icon: 💗 # Emoji or false
  author_link: /aboutme # Url for the link of author
  runtime: true # Whether to show website running time
  statistic: true # Whether to show site statistics(total articles & total wordcount)
  # Site register info(e.g. ICP)
  register_info:
    enable: false # Whether to show register info
    record_info: 京ICP备………………号 # E.g. ICP record number
    query_url: https://beian.miit.gov.cn/ # E.g. ICP record url

# CDN Configuration
cdn:
  # Whether to enable CDN
  enable: true
  # CDN provider
  provider: npmmirror # npmmirror, cdnjs, jsdelivr, unpkg, custom
  # Custom CDN url, should be formatted. Example: https://cdn.jsdelivr.net/npm/${jsname}@${version}/${path}
  custom: